spring:
  datasource:
    url: jdbc:mysql://localhost:3306/correios
    username: root
    password: lucas
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  error:
    include-message: always